### ISSUE TITLE
Pulling error: "abort: could not find web.cacerts:..."

### ISSUE THREAD

**Issue by arhohryakov** [cosmomill/SourceTreePortable#2]
When i choose pull, the SourceTree shows me an error message:
"abort: could not find web.cacerts: C:
Users<user>\AppData\Local\Atlassian\SourceTree\hg_local\cacert.pem"
This file exists at portable location: D:\PortableApps\SourceTreePortable\Data\ClientFiles\SourceTree\hg_local\cacert.pem
Why does SourceTreePortable can't find it?

**Comment by cosmomill** [comment]
If SourceTree portable is running the content of "D:\PortableApps\SourceTreePortable\Data\ClientFiles\SourceTree" sould be moved to "Users<user>\AppData\Local\Atlassian\SourceTree". Did you always run SourceTreeProtable.exe?
