### ISSUE TITLE
Not killing task after close

### ISSUE THREAD

**Issue by Rocket-Fish** [cosmomill/SourceTreePortable#3]
I am not sure if this is a bug or is this something wrong with windows 10. 

I have successfully installed this thing and it works perfectly until closing the application, and restarting it.

It closes but it doesn't kill the task. This results in the "Another Instance is still running" error. If I kill the application with task manager or taskkill, the next time I run it, the application would clean up. Still resulting in the inability to start the user interface (due to the fact that it doesn't close properly).

**Comment by cosmomill** [comment]
Which task is still running? "SourceTree.exe" or "SourceTreePortable.exe".

**Comment by Trippley** [comment]
It's the SourceTreePortable.exe

**Comment by cosmomill** [comment]
I will setup a Windows 10 test system here and see if I can reproduce this.

**Comment by cosmomill** [comment]
Fixed in f6e3e869bedd84599bb5239891695ae4de675fc7
