### ISSUE TITLE
Not entirely portable

### ISSUE THREAD

**Issue by docterry** [cosmomill/SourceTreePortable#4]
Copies files from Data\ClientFiles into %LocalAppData%\Atlassian on launch, then back again on close.

Is there a way for STP to use the files in ClientFiles rather than copying back and forth? Network drive copy is slow and takes several mintues to launch and close SourceTree.

**Comment by cosmomill** [comment]
No, at least I didn't find a way yet. Copy files back and forth, this is how portable apps works.
